apiVersion: v1
kind: Service
metadata:
  name: infoline-api-service
  namespace: default
  labels:
    app: infoline-api
spec:
  type: ClusterIP
  selector:
    app: infoline-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
