apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infoline-frontend-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.infoline.example.com
    secretName: infoline-frontend-tls
  rules:
  - host: www.infoline.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: infoline-frontend-service
            port:
              number: 80