apiVersion: v1
kind: Service
metadata:
  name: infoline-frontend-service
  namespace: default
  labels:
    app: infoline-frontend
spec:
  type: ClusterIP
  selector:
    app: infoline-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
